### ISSUE TITLE
Add link to repository or contact information to website 

### ISSUE THREAD

**Issue by ann0see** [mcfnord/JamFan22#3]
For a long time I didn’t know who was responsible for jamulus.live. I think there should be a way to know who the author of the website is. This also makes the site more trustworthy.

**Comment by mcfnord** [comment]
I've added a **Contact us** section with an email address that will appear when the code updates.

I'll probably get some annoying letters, but maybe some useful ones, too. I bet I'll need to re-direct some to the official site. We'll see.

I like verbal interactions better, because verbally, it's a bit harder to ride the crazy train, and even if you do, it's interesting and informative to hear. I got one angry verbal complaint. It's somewhat easier to understand and empathize with people's angry spoken words, vs. their angry typing. So I like the idea of inviting people to come find me for verbal interaction, but for now I've provided an email address.

I've recognized that the site holds real power, and a burden of power is hearing criticism and complaints, including unbalanced ones.

I prefer the unhinged and deeply misleading GitHub discussions about my code. None of those crazy people have tried verbally engaging with me 1:1, or sharing their concerns in a clear typed letter. So maybe the emails won't be so crazy.

**Comment by ann0see** [comment]
Actually, I wouldn't publish the E-Mail as this gets you spammed after thinking more about it. Why not just link your website/GitHub profile?

**Comment by mcfnord** [comment]
I know it's likely to get harvested, but it's a disposable address. So I'm inquiring as to the state of spam spiders. Sometimes I place the email address as an image so it won't be harvested. I wouldn't say it's easy to reach me via github... get an account and all that.

**Comment by ann0see** [comment]
Hmm. Then probably an image would be better. Personally, I **hate** getting spam.
